### PR TITLE
Tanimoto distance distribution for a dataframe input

### PR DESCRIPTION
**Pull request by ravichas**
I found this function in one of the notebooks, I made few changes and tested it. The function takes in a data frame and computes fingerprints --> Tanimoto distances and plots distance distribution. I think the function will be useful for EDA analysis.

### CODE REVIEW

**Comment by stewarthe6** [comment]
I propose that we merge this into 1.2.0. Otherwise I have no comments.

**Comment by das046** [comment]
I agree with Stewart. Ravi, could you close this PR and create a new one to merge it into 1.2.0 branch?

**Comment by stewarthe6** [comment]
I can change the target branch from here. Merge complete.

**Comment by stewarthe6** [comment]
I inadvertently merged some of master into 1.2.0 with that merge. I think that's ok though.

**Pull request merged**
