### PR TITLE
Tutorials

### PR DESCRIPTION
**Pull request by ravichas**
I have created a folder called **_tutorials_** under **_atomsci/ddm/examples_** and pushed the 14 Jupyterlab tutorial notebooks there. Certain dataset files are still pointing to my GitHub, which I will fix after Jonathan's talk. Right now, it seems everything is working. Thank you, Amanda, Da, Jonathan, and Stewart for all the help.

### CODE REVIEW

**Review by paulsonak — COMMENTED** [review]
This looks good to me for an initial commit. Over the next week I will be reviewing these to pass on to the Butler students and will make a few more changes & help clean some of the notebooks up.

**Comment by stewarthe6** [comment]
There are a few files that are copied into tutorials/configs

examples/tutorials/config/dist_metrics.py
examples/tutorials/config/diversity_plots.py 
examples/tutorials/config/struct_utils.py 

Are these the same files found in AMPL?

**Comment by ravichas** [comment]
Yes, we were using it for a stand-alone COLAB (non-AMPL) notebook. I will try to clean this up. Thanks.

**Comment by ravichas** [comment]
**@stewarthe6** 
To address your comments, I have removed the *py from the `examples/tutorials/config,` directory

**Review by stewarthe6 — APPROVED** [review]
Looks good to me. I'll merge it into master around 11am in case Da or Jonathan has anything to say.

**Comment by ravichas** [comment]
Thanks Stewart

**Comment by das046** [comment]
Are all the installation scripts (install_AMPL_*.sh) files needed in the notebooks? Could you remove the unnecessary ones? Just to keep it simple.

**Comment by das046** [comment]
Other than that, it looks great!

**Review by das046 — APPROVED** [review]

**Comment by ravichas** [comment]
@das046 
Good comments, I have made (deleted) the necessary changes. Thanks

**Pull request merged**
